
var e;e||(e=typeof Module !== 'undefined' ? Module : {});String.prototype.startsWith||(String.prototype.startsWith=function(a){return 0==this.lastIndexOf(a,0)});String.prototype.includes||(String.prototype.includes=function(a,b){return b?0<=this.indexOf(a,b):0<=this.indexOf(a)});var k,aa,l,n,ba,p,q,r,da,ea,fa,ha,ia,ja,t,ka,la,u,v,ma,na,w,x,oa,pa,y,z,A,C,D,E;function qa(a){q.famobi?q.famobi.log(a):q.console.log(a)}
function ra(){var a=(k.createGain||k.createGainNode).call(k),b={};a.connect(k.destination);b.wb=a;b.rb=1;b.jb=0;b.tb=1;return b}function sa(a,b,c){try{a.tb=b,a.wb.gain.value=b*c}catch(d){}}
function ta(a,b,c,d){var f;var g=n.length;for(f=0;f<g;f++){var h=n[f];if(!h.lb||h.rb)break}if(f==g)if(64>g)n[g]=ra();else return 0;h=n[f];h.rb=0;h.src=k.createBufferSource();h.src.loop=a.xb;h.src.playbackRate.value=d;h.src.connect(h.wb);h.src.onended=function(){h.rb=1};h.src.buffer=a.buffer;h.lb=a;sa(h,b,c);(h.src.start||h.src.noteOn).call(h.src,0);16777215<=ba?ba=1:ba++;h.jb=f+128*ba;return h.jb}function ua(){va()}function wa(){ja=0;xa()}
function F(a){a=a||q.event;if(a.type in w)w[a.type]();else this[x]?wa():va()}function ya(){var a=oa,b=pa,c=za(Aa),d={Ib:c,attributes:b,version:b.Jb,vb:a};a.canvas&&(a.canvas.Eb=d);Aa[c]=d;("undefined"===typeof b.Cb||b.Cb)&&Ba(d);Ca=Aa[c];e.Fb=G=Ca&&Ca.vb;typeof r[x]!=E&&F({type:r[x]?"blur":"focus"});Da(ma)}
window.eso_init=function(a){na=a;ba=0;D="dat_";E="undefined";q=window;r=q.document;(a=q.AudioContext||q.webkitAudioContext)&&(k=new a);C=A=z=y=1;l=[];p=[];pa={alpha:0,depth:1,antialias:0,stencil:0};(oa=e.canvas.getContext("webgl",pa)||e.canvas.getContext("experimental-webgl",pa))||(r.body.innerHTML="<h1>This game requires browser with WebGL support!</h1>");a=q.navigator.userAgent;ha=a.match(/Android/i);a.match(/iPhone|iPad|iPod/i);(ia=a.match(/IEMobile/i))&&(ha=!1);v=ha?1:0;fa=ha&&typeof q.AudioContext==
E&&typeof q.webkitAudioContext!=E;t=q.devicePixelRatio||1;ka=la=0;q.eso_upd_cnv=Ea;q.eso_post_init=ya;if(k){aa=!!k.decodeAudioData;n=[];for(a=0;16>a;a++)n[a]=ra();a=new q.Audio;try{a.canPlayType("audio/ogg")&&(u=".ogg")}catch(b){}try{u||a.canPlayType("audio/mpeg")&&(u=".mp3")}catch(b){}u||(k=null)}ma="ontouchstart"in q||typeof q.navigator.msMaxTouchPoints!=E&&0<q.navigator.msMaxTouchPoints||typeof q.navigator.maxTouchPoints!=E&&0<q.navigator.maxTouchPoints;q.addEventListener("keydown",Fa,!1);q.addEventListener("keyup",
Ga,!1);a=e.canvas;ma&&(q.navigator.pointerEnabled?(a.addEventListener("pointerdown",Ha,!1),a.addEventListener("pointermove",Ia,!1),a.addEventListener("pointerup",Ja,!1)):q.navigator.msPointerEnabled?(a.addEventListener("MSPointerDown",Ha,!1),a.addEventListener("MSPointerMove",Ia,!1),a.addEventListener("MSPointerUp",Ja,!1)):(a.addEventListener("touchstart",Ka,!1),a.addEventListener("touchend",La,!1),a.addEventListener("touchcancel",La,!1),a.addEventListener("touchmove",Ma,!1)));a.addEventListener("mousedown",
Na,!1);a.addEventListener("mousemove",Oa,!1);a.addEventListener("mouseup",Pa,!1);x="hidden";x in r?r.addEventListener("visibilitychange",F):(x="mozHidden")in r?r.addEventListener("mozvisibilitychange",F):(x="webkitHidden")in r?r.addEventListener("webkitvisibilitychange",F):(x="msHidden")in r?r.addEventListener("msvisibilitychange",F):"onfocusin"in r?r.onfocusin=r.onfocusout=F:q.onpageshow=q.onpagehide=q.onfocus=q.onblur=F;w={};w.focus=ua;w.focusin=ua;w.pageshow=ua;w.blur=wa;w.focusout=wa;w.pagehide=
wa};function Ea(){var a=0,b=0;var c=r.documentElement;var d=c.clientWidth;c=c.clientHeight;fa&&typeof d!=E&&typeof c!=E&&(a=d,b=c);a||(a=q.innerWidth||1280);b||(b=q.innerHeight||720);a=Math.ceil(a);b=Math.ceil(b);d=a*t;c=b*t;if(4096<d||4096<c)d=a,c=b,t=1,ka=-1,qa("Screen dimensions are too big! Scaling down with device pixel ratio == 1");if(.625<Math.abs(d-ka)||.625<Math.abs(c-la)){ka=d;la=c;var f=e.canvas;f.style.width=a+"px";f.style.height=b+"px";f.width=d;f.height=c;Qa(ka,la)}}
function H(a){typeof a.stopPropagation!=E&&a.stopPropagation&&a.stopPropagation();typeof a.preventDefault!=E&&a.preventDefault&&a.preventDefault()}function Fa(a){var b=a.keyCode;Ra(b);if(32==b&&a.target==r.body)return H(a),0}function Ga(a){var b=a.keyCode;Sa(b);if(32==b&&a.target==r.body)return H(a),0}function Ta(a){try{if(0==v){try{a.kb.volume=a.volume*C}catch(b){}try{a.kb.muted=!z}catch(b){}a.kb.play()}else a.jb=ta(a,a.volume,C*z,1)}catch(b){}}
function Ua(){var a;for(a=0;a<n.length;a++){var b=n[a];if(b.lb){var c=b.lb.yb?C*z:A*y;sa(b,b.tb,c)}}}function Va(a,b){var c=new XMLHttpRequest;c.open("GET",I(a)+u);c.responseType="arraybuffer";c.onload=function(){var d=c.response;aa?k.decodeAudioData(d,function(f){b(f)},function(f){qa("decodeAudioData error: "+(f&&f.err||"null"));b(k.createBuffer(1,1,11025))}):b(k.createBuffer(d,!1))};c.send()}
function Wa(){if(k&&!ja){var a=k.createBuffer(1,1,22050),b=k.createBufferSource();b.buffer=a;b.connect(k.destination);(b.start||b.noteOn).call(b,0,0,0);q.setTimeout(function(){if(b.playbackState==b.PLAYING_STATE||b.playbackState==b.FINISHED_STATE){ja=!0;for(var c=0,d;c<p.length;c++)(d=p[c])&&d.sb&&(1==v&&Xa(Ya(d.jb),d.jb),Ta(d))}},0)}}function J(a,b,c){a(b.clientX*t,b.clientY*t,c)}function Ka(a){Wa();for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b];J(Za,c,c.identifier)}H(a)}
function Ma(a){for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b];J(ab,c,c.identifier)}H(a)}function La(a){for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b];J(bb,c,c.identifier)}H(a)}function Ha(a){a.pointerType!==a.MSPOINTER_TYPE_MOUSE&&"mouse"!==a.pointerType&&(H(a),J(Za,a,a.pointerId))}function Ia(a){a.pointerType!==a.MSPOINTER_TYPE_MOUSE&&"mouse"!==a.pointerType&&(H(a),J(ab,a,a.pointerId))}
function Ja(a){a.pointerType!==a.MSPOINTER_TYPE_MOUSE&&"mouse"!==a.pointerType&&(H(a),J(bb,a,a.pointerId))}function Na(a){var b=e.canvas;r.activeElement!=b&&b.focus();Wa();H(a);J(Za,a,-2)}function Oa(a){H(a);J(ab,a,-2)}function Pa(a){H(a);J(bb,a,-2)}function Xa(a,b){if(b&&a&&a.jb==b){try{(a.src.stop||a.src.noteOff).call(a.src,0)}catch(c){}a.jb=0}}function Ya(a){if(a){var b=a&127;if(b<n.length&&(b=n[b],b.jb==a))return b}return null}var K,cb,db,eb,fb;function gb(a){return K&&K.hasFeature(a)||0}
function L(a,b){if(cb)return cb.trackEvent(a,b)}function hb(a,b){if(db){var c=db.EVENTS;c&&db.trackEvent(c[a],b)}}function ib(){K&&K.showInterstitialAd()}function jb(a){var b;if(K&&(b=K.getFeatureProperties("forced_mode"))){var c=(c=b.state)&&c[a];if(typeof c!=E)return c;c=(c=b.override)&&c[a];if(typeof c!=E)return c}}function kb(a){return typeof jb(a)!=E}
window.famobi_init=function(){(K=q.famobi)?(eb=K.getBrandingButtonImage(),q.famobi_onPauseRequested=function(){M(6,1)},q.famobi_onResumeRequested=function(){M(6,0)}):eb="tex/famobi_branding_button.png";cb=q.famobi_analytics;(db=q.famobi_tracking)&&db.init("e-scooter",null,0,!1,!0)};var lb={},O;for(O in e)e.hasOwnProperty(O)&&(lb[O]=e[O]);var mb="object"===typeof window,nb="function"===typeof importScripts,P="",ob,pb,qb,Q,R;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)P=nb?require("path").dirname(P)+"/":__dirname+"/",ob=function(a,b){Q||(Q=require("fs"));R||(R=require("path"));a=R.normalize(a);return Q.readFileSync(a,b?null:"utf8")},qb=function(a){a=ob(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||rb("Assertion failed: undefined");return a},pb=function(a,b,c){Q||(Q=require("fs"));R||(R=require("path"));a=R.normalize(a);Q.readFile(a,function(d,f){d?c(d):b(f.buffer)})},
1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;}),e.inspect=function(){return"[Emscripten Module object]"};else if(mb||nb)nb?P=self.location.href:"undefined"!==typeof document&&document.currentScript&&(P=document.currentScript.src),P=0!==P.indexOf("blob:")?P.substr(0,P.replace(/[?#].*/,"").lastIndexOf("/")+1):"",
ob=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},nb&&(qb=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pb=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var sb=e.printErr||console.warn.bind(console);
for(O in lb)lb.hasOwnProperty(O)&&(e[O]=lb[O]);lb=null;var tb;e.wasmBinary&&(tb=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&rb("no native wasm support detected");var ub,vb=!1,wb="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function I(a,b){if(a){var c=xb,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&wb)a=wb.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var g=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function yb(a,b,c){var d=xb;if(!(0<c))return 0;var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-f}var xb,zb,S,Ab,T,Bb,Cb=[],Db=[],Eb=[];
function Fb(){var a=e.preRun.shift();Cb.unshift(a)}var U=0,Gb=null,Hb=null;e.preloadedImages={};e.preloadedAudios={};function rb(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";sb(a);vb=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ib(){return V.startsWith("data:application/octet-stream;base64,")}var V;V="app.wasm";if(!Ib()){var Jb=V;V=e.locateFile?e.locateFile(Jb,P):P+Jb}
function Kb(){var a=V;try{if(a==V&&tb)return new Uint8Array(tb);if(qb)return qb(a);throw"both async and sync fetching of the wasm failed";}catch(b){rb(b)}}
function Lb(){if(!tb&&(mb||nb)){if("function"===typeof fetch&&!V.startsWith("file://"))return fetch(V,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+V+"'";return a.arrayBuffer()}).catch(function(){return Kb()});if(pb)return new Promise(function(a,b){pb(V,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Kb()})}
function Mb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Hb;"number"===typeof c?void 0===b.qb?Bb.get(c)():Bb.get(c)(b.qb):c(void 0===b.qb?null:b.qb)}}}function Nb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function Ob(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Pb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Qb=1,Rb=[],W=[],Sb=[],X=[],Aa=[],Tb={},Vb=4;function Y(a){Wb||(Wb=a)}
function za(a){for(var b=Qb++,c=a.length;c<b;c++)a[c]=null;return b}function Ba(a){a||(a=Ca);if(!a.Db){a.Db=!0;var b=a.vb;Nb(b);Ob(b);Pb(b);b.Gb=b.getExtension("EXT_disjoint_timer_query");b.Kb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Wb,Ca;function Xb(a,b,c,d){for(var f=0;f<a;f++){var g=G[c](),h=g&&za(d);g?(g.name=h,d[h]=g):Y(1282);S[b+4*f>>2]=h}}
function Yb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b+=1;c=Zb(b);yb(a,c,b);return c}function $b(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function ac(a){var b=G.Bb;if(b){var c=b.mb[a];"number"===typeof c&&(b.mb[a]=c=G.getUniformLocation(b,b.zb[a]+(0<c?"["+c+"]":"")));return c}Y(1282)}for(var bc=[],G,cc=new Float32Array(288),dc=0;288>dc;++dc)bc[dc]=cc.subarray(0,dc+1);
var ic={M:function(a,b,c){xb.copyWithin(a,b,b+c)},t:function(){rb("OOM")},w:function(a,b,c){var d=new q.XMLHttpRequest;d.open("GET",I(a),!0);d.responseType="arraybuffer";d.onload=function(){var f=new Uint8Array(d.response),g=f.length*f.BYTES_PER_ELEMENT,h=Zb(g),m=new Uint8Array(e.HEAPU8.buffer,h,g);m.set(f);e[I(b)](c,m.byteOffset,g);ec(h)};d.send()},qa:function(a,b){a=I(a);if(na){var c=a.length-3;"png"==a.slice(c)&&(a=a.slice(0,c)+"webp")}c=new Image;if("famobi_branding_button"==a.substring(4,26)){var d=
a;a=eb;c.crossOrigin="anonymous";c.onerror=function(){c.src=d}}c.src=a;c.onload=function(){da=c;fc(b)}},na:function(a){ea-=a;0<=ea||(ea=.5,Ea())},Aa:function(a,b){G.texImage2D(G.TEXTURE_2D,0,a,a,b,da);da=0},oa:function(a,b){function c(h){for(var m=0;p[m];m++);0==v?p[m]={kb:h}:(p[m]={buffer:h,xb:1},p[m].yb=1);gc(b,m)}function d(){f||(c(g),f=1)}var f;if(k)if(0==v){var g=new q.Audio;g.preload="auto";g.loop=1;g.oncanplaythrough=d;g.src=I(a)+u;g.load();q.setTimeout(d,4800)}else Va(a,c);else c()},ha:function(a){C=
a;if(0==v){a=0;for(var b;a<p.length;a++)if((b=p[a])&&b.sb)try{b.kb.volume=b.volume*C}catch(c){}}else Ua()},sa:function(a,b){k&&0<=a&&a<p.length&&(a=p[a])&&(a.sb=1,a.volume=b,Ta(a))},va:function(a){if(k){z=a;for(var b=0,c;b<p.length;b++)if((c=p[b])&&c.sb)if(0==v){try{c.kb.volume=c.volume*C}catch(f){}try{c.kb.muted=!a}catch(f){}}else{var d=Ya(c.jb);d&&sa(d,c.volume,z*C)}}},ga:function(){return(new Date).getTime()|0},ra:function(a){l[a]=null},pa:function(a,b,c){function d(f){var g;for(g=0;l[g];g++);
l[g]={buffer:f,xb:c};hc(b,g)}k?Va(a,d):d()},ia:function(a){A=a;Ua()},H:function(a,b,c){return k&&0<=a&&a<l.length?ta(l[a],b,A*y,c):0},ua:function(a,b){k&&(a=Ya(a))&&(a.src.playbackRate.value=b)},r:function(a){k&&Xa(Ya(a),a)},wa:function(a){if(k)for(y=a,a=0;a<n.length;a++){var b=n[a];b.lb&&!b.lb.yb&&sa(b,b.tb,A*y)}},ta:function(a,b){k&&(a=Ya(a))&&sa(a,b,A*y)},V:function(a){function b(){M(8,0)}K?L(a?"EVENT_LEVELRESTART":"EVENT_LEVELSTART",{levelName:""}).then(b):b()},T:function(){return gb("external_mute")},
W:function(){return gb("external_pause")},ka:function(a){return K?(a=K.localStorage.getItem(D+a))&&0<a.length:(a=q.localStorage.getItem(D+a))&&0<a.length},v:function(){return gb("forced_mode")},Z:function(a){var b=0;a=I(a);kb(a)&&(b=jb(a).length||0);return b},X:function(a,b,c){var d="";a=I(a);kb(a)&&(d+=jb(a)[b]||"");b=e.HEAPU8;for(a=0;a<d.length&&!(b[c++]=d.charCodeAt(a),61<a);a++);b[c]=0},u:function(a){a=I(a);return kb(a)?jb(a):0},_:function(a,b){var c=I(a),d;a=e.HEAPU8;if(kb(c))for(c=jb(c),d=0;d<
c.length&&!(a[b++]=c.charCodeAt(d),61<d);d++);a[b]=0},N:function(a){var b;var c=e.HEAPU8;if(K){var d=K.getCurrentLanguage();d=""+d;for(b=0;b<d.length&&!(c[a++]=d.charCodeAt(b),61<b);b++);}c[a]=0},p:function(a){return kb(I(a))},$:function(){return gb("copyright")},la:function(a,b,c){if(K){var d=D+a;if(a=K.localStorage.getItem(D+a))if(c!=a.length)qa("eso_lodd: size mismatch in "+d);else for(c=0;c<a.length;c++)e.HEAPU8[b++]=a.charCodeAt(c)}else if(d=D+a,a=q.localStorage.getItem(D+a))if(c!=a.length)qa("eso_lodd: size mismatch in "+
d);else for(c=0;c<a.length;c++)e.HEAPU8[b++]=a.charCodeAt(c)},U:function(){K&&K.openBrandingLink()},R:function(){function a(){M(9,0)}if(K){var b=L("EVENT_LEVELFAIL",{levelName:"",reason:"quit"});var c=ib();q.Promise.all([b,c]).then(a)}else a()},fa:function(){K&&K.gameReady()},ca:function(a){L("EVENT_LIVESCORE",{liveScore:a})},O:function(){K&&K.playerReady()},Q:function(a){function b(){K?(K.setPreloadProgress(fb),fb=0):q.setTimeout(b,1E3)}fb?fb=a:(fb=a,b())},ma:function(a,b,c){K?(b=e.HEAPU8.subarray(b,
b+c),b=q.String.fromCharCode.apply(q.String,b),K.localStorage.setItem(D+a,b)):(b=e.HEAPU8.subarray(b,b+c),b=q.String.fromCharCode.apply(q.String,b),q.localStorage.setItem(D+a,b))},ea:function(){return gb("skip_title")},S:function(a,b){L("EVENT_VOLUMECHANGE",{bgmVolume:a,sfxVolume:b})},ba:function(a,b){function c(){M(5,0)}K?L("EVENT_CUSTOM",{eventName:"LEVELEND",result:I(a),score:b}).then(c):c()},da:function(a,b){function c(){M(4,0)}if(K){hb("LEVEL_END",{success:a,score:b,level:""});a=L("EVENT_LEVELFAIL",
{levelName:"",reason:"timeout"});var d=ib();L("EVENT_TOTALSCORE",{totalScore:b});q.Promise.all([a,d]).then(c)}else c()},P:function(){hb("LEVEL_START",{level:1})},aa:function(a){hb("LEVEL_UPDATE",{score:a})},B:function(a){L(a?"EVENT_PAUSE":"EVENT_RESUME")},m:function(a,b){a=I(a);cb&&K.hasFeature("trackstats")&&cb.trackStats(a,{},b)},E:function(a){G.activeTexture(a)},A:function(a,b){G.attachShader(W[a],X[b])},Na:function(a,b,c){G.bindAttribLocation(W[a],b,I(c))},c:function(a,b){G.bindBuffer(a,Rb[b])},
e:function(a,b){G.bindTexture(a,Sb[b])},o:function(a,b){G.blendFunc(a,b)},j:function(a,b,c,d){G.bufferData(a,c?xb.subarray(c,c+b):b,d)},y:function(a){G.clear(a)},Fa:function(a,b,c,d){G.clearColor(a,b,c,d)},L:function(a){G.clearDepth(a)},F:function(a){G.compileShader(X[a])},Y:function(){var a=za(W),b=G.createProgram();b.name=a;b.pb=b.nb=b.ob=0;b.ub=1;W[a]=b;return a},I:function(a){var b=za(X);X[b]=G.createShader(a);return b},ya:function(a){G.cullFace(a)},Ga:function(a){if(a){var b=X[a];b?(G.deleteShader(b),
X[a]=null):Y(1281)}},Ba:function(a,b){for(var c=0;c<a;c++){var d=S[b+4*c>>2],f=Sb[d];f&&(G.deleteTexture(f),f.name=0,Sb[d]=null)}},D:function(a){G.depthMask(!!a)},i:function(a){G.disable(a)},z:function(a){G.disableVertexAttribArray(a)},q:function(a,b,c,d){G.drawElements(a,b,c,d)},f:function(a){G.enable(a)},g:function(a){G.enableVertexAttribArray(a)},J:function(a,b){Xb(a,b,"createBuffer",Rb)},K:function(a,b){Xb(a,b,"createTexture",Sb)},za:function(a){G.generateMipmap(a)},Ka:function(a,b,c,d){a=G.getProgramInfoLog(W[a]);
null===a&&(a="(unknown error)");b=0<b&&d?yb(a,d,b):0;c&&(S[c>>2]=b)},La:function(a,b,c){if(c)if(a>=Qb)Y(1281);else if(a=W[a],35716==b)a=G.getProgramInfoLog(a),null===a&&(a="(unknown error)"),S[c>>2]=a.length+1;else if(35719==b){if(!a.pb)for(b=0;b<G.getProgramParameter(a,35718);++b)a.pb=Math.max(a.pb,G.getActiveUniform(a,b).name.length+1);S[c>>2]=a.pb}else if(35722==b){if(!a.nb)for(b=0;b<G.getProgramParameter(a,35721);++b)a.nb=Math.max(a.nb,G.getActiveAttrib(a,b).name.length+1);S[c>>2]=a.nb}else if(35381==
b){if(!a.ob)for(b=0;b<G.getProgramParameter(a,35382);++b)a.ob=Math.max(a.ob,G.getActiveUniformBlockName(a,b).length+1);S[c>>2]=a.ob}else S[c>>2]=G.getProgramParameter(a,b);else Y(1281)},Ca:function(a,b,c,d){a=G.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?yb(a,d,b):0;c&&(S[c>>2]=b)},C:function(a,b,c){c?35716==b?(a=G.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),S[c>>2]=a?a.length+1:0):35720==b?(a=G.getShaderSource(X[a]),S[c>>2]=a?a.length+1:0):S[c>>2]=G.getShaderParameter(X[a],
b):Y(1281)},Ia:function(a){var b=Tb[a];if(!b){switch(a){case 7939:b=G.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Yb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||Y(1280);b=b&&Yb(b);break;case 7938:b=Yb("OpenGL ES 2.0 ("+G.getParameter(7938)+")");break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
Yb(b);break;default:Y(1280)}Tb[a]=b}return b},a:function(a,b){b=I(b);if(a=W[a]){var c=a,d=c.mb,f=c.Ab,g;if(!d)for(c.mb=d={},c.zb={},g=0;g<G.getProgramParameter(c,35718);++g){var h=G.getActiveUniform(c,g);var m=h.name;h=h.size;var B=$b(m);B=0<B?m.slice(0,B):m;var ca=c.ub;c.ub+=h;f[B]=[h,ca];for(m=0;m<h;++m)d[ca]=m,c.zb[ca++]=B}c=a.mb;d=0;f=b;g=$b(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.Ab[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||G.getUniformLocation(a,b)))return d}else Y(1281);return-1},
Ha:function(a){return(a=X[a])?G.isShader(a):0},Ma:function(a){a=W[a];G.linkProgram(a);a.mb=0;a.Ab={}},Da:function(a,b){3317==a&&(Vb=b);G.pixelStorei(a,b)},ja:function(a,b,c,d){G.scissor(a,b,c,d)},G:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?S[d+4*g>>2]:-1;f+=I(S[c+4*g>>2],0>h?void 0:h)}G.shaderSource(X[a],f)},Ea:function(a,b,c,d,f,g,h,m,B){var ca=G,lc=ca.texImage2D;if(B){var N=m-5120;N=1==N?xb:4==N?S:6==N?T:5==N||28922==N?Ab:zb;var $a=31-Math.clz32(N.BYTES_PER_ELEMENT),Ub=Vb;B=N.subarray(B>>
$a,B+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[h-6402]||1)*(1<<$a)+Ub-1&-Ub)>>$a)}else B=null;lc.call(ca,a,b,c,d,f,g,h,m,B)},n:function(a,b,c){G.texParameteri(a,b,c)},Ja:function(a,b){G.uniform1i(ac(a),b)},x:function(a,b,c,d){G.uniform3f(ac(a),b,c,d)},h:function(a,b,c,d,f){G.uniform4f(ac(a),b,c,d,f)},k:function(a,b,c){if(72>=b){var d=bc[4*b-1],f=T;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=f[h];d[g+1]=f[h+1];d[g+2]=f[h+2];d[g+3]=f[h+3]}}else d=T.subarray(c>>2,c+16*b>>2);G.uniform4fv(ac(a),d)},s:function(a,
b,c,d){if(32>=b)for(var f=bc[9*b-1],g=0;g<9*b;g+=9)f[g]=T[d+4*g>>2],f[g+1]=T[d+(4*g+4)>>2],f[g+2]=T[d+(4*g+8)>>2],f[g+3]=T[d+(4*g+12)>>2],f[g+4]=T[d+(4*g+16)>>2],f[g+5]=T[d+(4*g+20)>>2],f[g+6]=T[d+(4*g+24)>>2],f[g+7]=T[d+(4*g+28)>>2],f[g+8]=T[d+(4*g+32)>>2];else f=T.subarray(d>>2,d+36*b>>2);G.uniformMatrix3fv(ac(a),!!c,f)},l:function(a,b,c,d){if(18>=b){var f=bc[16*b-1],g=T;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;f[h]=g[m];f[h+1]=g[m+1];f[h+2]=g[m+2];f[h+3]=g[m+3];f[h+4]=g[m+4];f[h+5]=g[m+5];f[h+
6]=g[m+6];f[h+7]=g[m+7];f[h+8]=g[m+8];f[h+9]=g[m+9];f[h+10]=g[m+10];f[h+11]=g[m+11];f[h+12]=g[m+12];f[h+13]=g[m+13];f[h+14]=g[m+14];f[h+15]=g[m+15]}}else f=T.subarray(d>>2,d+64*b>>2);G.uniformMatrix4fv(ac(a),!!c,f)},b:function(a){a=W[a];G.useProgram(a);G.Bb=a},d:function(a,b,c,d,f,g){G.vertexAttribPointer(a,b,c,!!d,f,g)},xa:function(a,b,c,d){G.viewport(a,b,c,d)}};
(function(){function a(f){e.asm=f.exports;ub=e.asm.Oa;f=ub.buffer;e.HEAP8=new Int8Array(f);e.HEAP16=new Int16Array(f);e.HEAP32=S=new Int32Array(f);e.HEAPU8=xb=new Uint8Array(f);e.HEAPU16=zb=new Uint16Array(f);e.HEAPU32=Ab=new Uint32Array(f);e.HEAPF32=T=new Float32Array(f);e.HEAPF64=new Float64Array(f);Bb=e.asm.ib;Db.unshift(e.asm.Pa);U--;e.monitorRunDependencies&&e.monitorRunDependencies(U);0==U&&(null!==Gb&&(clearInterval(Gb),Gb=null),Hb&&(f=Hb,Hb=null,f()))}function b(f){a(f.instance)}function c(f){return Lb().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(f,function(g){sb("failed to asynchronously prepare wasm: "+g);rb(g)})}var d={a:ic};U++;e.monitorRunDependencies&&e.monitorRunDependencies(U);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return sb("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return tb||"function"!==typeof WebAssembly.instantiateStreaming||Ib()||V.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(V,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(g){sb("wasm streaming compile failed: "+g);sb("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.Pa).apply(null,arguments)};
var Zb=e._malloc=function(){return(Zb=e._malloc=e.asm.Qa).apply(null,arguments)},ec=e._free=function(){return(ec=e._free=e.asm.Ra).apply(null,arguments)},hc=e._sw_snd_ld=function(){return(hc=e._sw_snd_ld=e.asm.Sa).apply(null,arguments)},gc=e._sw_mus_ld=function(){return(gc=e._sw_mus_ld=e.asm.Ta).apply(null,arguments)},fc=e._sw_tex_ld=function(){return(fc=e._sw_tex_ld=e.asm.Ua).apply(null,arguments)};e._sw_fnt_ld=function(){return(e._sw_fnt_ld=e.asm.Va).apply(null,arguments)};
e._sw_mdl_ld=function(){return(e._sw_mdl_ld=e.asm.Wa).apply(null,arguments)};e._sw_txt_ld=function(){return(e._sw_txt_ld=e.asm.Xa).apply(null,arguments)};e._sw_init=function(){return(e._sw_init=e.asm.Ya).apply(null,arguments)};var Qa=e._sw_cnv_upd=function(){return(Qa=e._sw_cnv_upd=e.asm.Za).apply(null,arguments)};e._sw_tick=function(){return(e._sw_tick=e.asm._a).apply(null,arguments)};
var Ra=e._sw_key_dwn=function(){return(Ra=e._sw_key_dwn=e.asm.$a).apply(null,arguments)},Sa=e._sw_key_up=function(){return(Sa=e._sw_key_up=e.asm.ab).apply(null,arguments)},Za=e._sw_tch_beg=function(){return(Za=e._sw_tch_beg=e.asm.bb).apply(null,arguments)},bb=e._sw_tch_end=function(){return(bb=e._sw_tch_end=e.asm.cb).apply(null,arguments)},ab=e._sw_tch_mov=function(){return(ab=e._sw_tch_mov=e.asm.db).apply(null,arguments)},Da=e._sw_sys_info=function(){return(Da=e._sw_sys_info=e.asm.eb).apply(null,
arguments)},xa=e._sw_susp=function(){return(xa=e._sw_susp=e.asm.fb).apply(null,arguments)},va=e._sw_resm=function(){return(va=e._sw_resm=e.asm.gb).apply(null,arguments)},M=e._fm_cb=function(){return(M=e._fm_cb=e.asm.hb).apply(null,arguments)},jc;Hb=function kc(){jc||mc();jc||(Hb=kc)};
function mc(){function a(){if(!jc&&(jc=!0,e.calledRun=!0,!vb)){Mb(Db);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Eb.unshift(b)}Mb(Eb)}}if(!(0<U)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fb();Mb(Cb);0<U||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=mc;
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();mc();function Z(a,b){if(K)K.onRequest(a,b)}Z("enableAudio",function(){M(0,1)});Z("disableAudio",function(){M(0,0)});Z("enableMusic",function(){M(1,1)});Z("disableMusic",function(){M(1,0)});function nc(a){M(2,65535*a|0)}Z("changeVolume",nc);K&&nc(K.getVolume());Z("pauseGameplay",function(){M(3,1)});Z("resumeGameplay",function(){M(3,0)});Z("startGame",function(){M(7,0)});
